// File generated by SD Sync Generator. DO NOT EDIT

use super::prisma::*;
use prisma_client_rust::scalar_types::*;
impl statistics::SetParam {
	pub fn deserialize(field: &str, val: ::rmpv::Value) -> Option<Self> {
		Some(match field {
			statistics::id::NAME => statistics::id::set(::rmpv::ext::from_value(val).unwrap()),
			statistics::date_captured::NAME => {
				statistics::date_captured::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_object_count::NAME => {
				statistics::total_object_count::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::library_db_size::NAME => {
				statistics::library_db_size::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_local_bytes_used::NAME => {
				statistics::total_local_bytes_used::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_local_bytes_capacity::NAME => {
				statistics::total_local_bytes_capacity::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_local_bytes_free::NAME => {
				statistics::total_local_bytes_free::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_library_bytes::NAME => {
				statistics::total_library_bytes::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_library_unique_bytes::NAME => {
				statistics::total_library_unique_bytes::set(::rmpv::ext::from_value(val).unwrap())
			}
			statistics::total_library_preview_media_bytes::NAME => {
				statistics::total_library_preview_media_bytes::set(
					::rmpv::ext::from_value(val).unwrap(),
				)
			}
			_ => return None,
		})
	}
}
impl statistics::UniqueWhereParam {
	pub fn deserialize(field: &str, val: ::rmpv::Value) -> Option<Self> {
		Some(match field {
			statistics::id::NAME => statistics::id::equals(::rmpv::ext::from_value(val).unwrap()),
			_ => return None,
		})
	}
}
