// File generated by Prisma Client Rust. DO NOT EDIT

use super::super::{_prisma::*, *};
use super::{SetParam, UncheckedSetParam, UniqueWhereParam, WhereParam, WithParam};
pub const NAME: &str = "label_objects";
pub type Type = Vec<label_on_object::Data>;
pub type RecursiveSafeType = Type;
pub fn some(value: Vec<label_on_object::WhereParam>) -> WhereParam {
	WhereParam::LabelObjectsSome(value)
}
pub fn every(value: Vec<label_on_object::WhereParam>) -> WhereParam {
	WhereParam::LabelObjectsEvery(value)
}
pub fn none(value: Vec<label_on_object::WhereParam>) -> WhereParam {
	WhereParam::LabelObjectsNone(value)
}
pub struct Order(Vec<label_on_object::OrderByRelationAggregateParam>);
pub fn order<T: From<Order>>(v: Vec<label_on_object::OrderByRelationAggregateParam>) -> T {
	Order(v).into()
}
impl From<Order> for super::OrderByWithRelationParam {
	fn from(Order(v): Order) -> Self {
		Self::LabelObjects(v)
	}
}
pub struct Fetch(pub label_on_object::ManyArgs);
impl Fetch {
	pub fn with(mut self, params: impl Into<label_on_object::WithParam>) -> Self {
		self.0 = self.0.with(params.into());
		self
	}
	pub fn order_by(mut self, param: label_on_object::OrderByWithRelationParam) -> Self {
		self.0 = self.0.order_by(param);
		self
	}
	pub fn skip(mut self, value: i64) -> Self {
		self.0 = self.0.skip(value);
		self
	}
	pub fn take(mut self, value: i64) -> Self {
		self.0 = self.0.take(value);
		self
	}
	pub fn cursor(mut self, value: label_on_object::UniqueWhereParam) -> Self {
		self.0 = self.0.cursor(value.into());
		self
	}
}
impl From<Fetch> for WithParam {
	fn from(Fetch(v): Fetch) -> Self {
		WithParam::LabelObjects(v)
	}
}
pub fn fetch(params: Vec<label_on_object::WhereParam>) -> Fetch {
	Fetch(label_on_object::ManyArgs::new(params))
}
pub struct Connect(pub Vec<label_on_object::UniqueWhereParam>);
impl From<Connect> for SetParam {
	fn from(Connect(v): Connect) -> Self {
		Self::ConnectLabelObjects(v)
	}
}
pub fn connect<T: From<Connect>>(params: Vec<label_on_object::UniqueWhereParam>) -> T {
	Connect(params).into()
}
pub fn disconnect(params: Vec<label_on_object::UniqueWhereParam>) -> SetParam {
	SetParam::DisconnectLabelObjects(params)
}
pub fn set(params: Vec<label_on_object::UniqueWhereParam>) -> SetParam {
	SetParam::SetLabelObjects(params)
}
pub enum Select {
	Select(label_on_object::ManyArgs, Vec<label_on_object::SelectParam>),
	Include(
		label_on_object::ManyArgs,
		Vec<label_on_object::IncludeParam>,
	),
	Fetch(label_on_object::ManyArgs),
}
impl Into<super::SelectParam> for Select {
	fn into(self) -> super::SelectParam {
		super::SelectParam::LabelObjects(self)
	}
}
impl Select {
	pub fn select(
		args: label_on_object::ManyArgs,
		nested_selections: Vec<label_on_object::SelectParam>,
	) -> Self {
		Self::Select(args, nested_selections)
	}
	pub fn include(
		args: label_on_object::ManyArgs,
		nested_selections: Vec<label_on_object::IncludeParam>,
	) -> Self {
		Self::Include(args, nested_selections)
	}
}
impl Into<::prisma_client_rust::Selection> for Select {
	fn into(self) -> ::prisma_client_rust::Selection {
		let (args, selections) = match self {
			Self::Select(args, selections) => (
				args.to_graphql().0,
				selections.into_iter().map(Into::into).collect(),
			),
			Self::Include(args, selections) => (args.to_graphql().0, {
				let mut nested_selections = vec![];
				nested_selections.extend(selections.into_iter().map(Into::into));
				nested_selections
			}),
			Self::Fetch(args) => (
				args.to_graphql().0,
				<label_on_object::Types as ::prisma_client_rust::ModelTypes>::scalar_selections(),
			),
		};
		::prisma_client_rust::Selection::new(NAME, None, args, selections)
	}
}
pub enum Include {
	Select(label_on_object::ManyArgs, Vec<label_on_object::SelectParam>),
	Include(
		label_on_object::ManyArgs,
		Vec<label_on_object::IncludeParam>,
	),
	Fetch(label_on_object::ManyArgs),
}
impl Into<super::IncludeParam> for Include {
	fn into(self) -> super::IncludeParam {
		super::IncludeParam::LabelObjects(self)
	}
}
impl Include {
	pub fn select(
		args: label_on_object::ManyArgs,
		nested_selections: Vec<label_on_object::SelectParam>,
	) -> Self {
		Self::Select(args, nested_selections)
	}
	pub fn include(
		args: label_on_object::ManyArgs,
		nested_selections: Vec<label_on_object::IncludeParam>,
	) -> Self {
		Self::Include(args, nested_selections)
	}
}
impl Into<::prisma_client_rust::Selection> for Include {
	fn into(self) -> ::prisma_client_rust::Selection {
		let (args, selections) = match self {
			Self::Select(args, selections) => (
				args.to_graphql().0,
				selections.into_iter().map(Into::into).collect(),
			),
			Self::Include(args, selections) => {
				(args.to_graphql().0, {
					let mut nested_selections = < label_on_object :: Types as :: prisma_client_rust :: ModelTypes > :: scalar_selections () ;
					nested_selections.extend(selections.into_iter().map(Into::into));
					nested_selections
				})
			}
			Self::Fetch(args) => (
				args.to_graphql().0,
				<label_on_object::Types as ::prisma_client_rust::ModelTypes>::scalar_selections(),
			),
		};
		::prisma_client_rust::Selection::new(NAME, None, args, selections)
	}
}
