[package]
authors       = ["Arnab Chakraborty <arnab@spacedrive.com>", "Del Wang <hello@xbox.work>"]
description   = "Enabling Cross-Origin Resource Sharing (CORS) for Fetch Requests within Tauri applications. Modified to work with Spacedrive and Supertokens for authentication."
documentation = "https://docs.rs/crate/tauri-plugin-cors-fetch"
edition       = "2021"
keywords      = ["CORS", "fetch", "tauri-plugin", "unofficial"]
license       = "MIT"
links         = "tauri-plugin-cors-fetch"
name          = "tauri-plugin-cors-fetch"
readme        = "README.md"
repository    = "https://github.com/idootop/tauri-plugin-cors-fetch"
rust-version  = "1.70"
version       = "2.1.1-sd-custom"

[dependencies]
http       = "0.2"
once_cell  = "1.19.0"
reqwest    = "0.11"
sd-crypto  = { path = "../crypto" }
serde      = { version = "1", features = ["derive"] }
serde_json = "1"
tauri      = "2.0.0-beta.11"
thiserror  = "1"
tokio      = { version = "1.36.0", features = ["macros"] }
tracing    = { workspace = true }
url        = "2"

[build-dependencies]
tauri-plugin = { version = "2.0.0-beta.9", features = ["build"] }

[package.metadata.docs.rs]
rustc-args   = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]
