/* eslint-disable */
// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "buildInfo", input: never, result: BuildInfo } | 
        { key: "files.get", input: LibraryArgs<GetArgs>, result: { id: number, pub_id: number[], name: string | null, extension: string | null, kind: number, size_in_bytes: string, key_id: number | null, hidden: boolean, favorite: boolean, important: boolean, has_thumbnail: boolean, has_thumbstrip: boolean, has_video_preview: boolean, ipfs_id: string | null, note: string | null, date_created: string, date_modified: string, date_indexed: string, file_paths: FilePath[], media_data: MediaData | null } | null } | 
        { key: "jobs.getHistory", input: LibraryArgs<null>, result: JobReport[] } | 
        { key: "jobs.getRunning", input: LibraryArgs<null>, result: JobReport[] } | 
        { key: "jobs.isRunning", input: LibraryArgs<null>, result: boolean } | 
        { key: "keys.getDefault", input: LibraryArgs<null>, result: string | null } | 
        { key: "keys.getKey", input: LibraryArgs<string>, result: string } | 
        { key: "keys.getSecretKey", input: LibraryArgs<null>, result: string | null } | 
        { key: "keys.isKeyManagerUnlocking", input: LibraryArgs<null>, result: boolean | null } | 
        { key: "keys.isUnlocked", input: LibraryArgs<null>, result: boolean } | 
        { key: "keys.list", input: LibraryArgs<null>, result: StoredKey[] } | 
        { key: "keys.listMounted", input: LibraryArgs<null>, result: string[] } | 
        { key: "library.getStatistics", input: LibraryArgs<null>, result: Statistics } | 
        { key: "library.list", input: never, result: LibraryConfigWrapped[] } | 
        { key: "locations.getById", input: LibraryArgs<number>, result: { id: number, pub_id: number[], node_id: number, name: string, path: string, total_capacity: number | null, available_capacity: number | null, is_archived: boolean, generate_preview_media: boolean, sync_preview_media: boolean, hidden: boolean, date_created: string, indexer_rules: IndexerRulesInLocation[] } | null } | 
        { key: "locations.getExplorerData", input: LibraryArgs<LocationExplorerArgs>, result: ExplorerData } | 
        { key: "locations.indexer_rules.get", input: LibraryArgs<number>, result: IndexerRule } | 
        { key: "locations.indexer_rules.list", input: LibraryArgs<null>, result: IndexerRule[] } | 
        { key: "locations.indexer_rules.listForLocation", input: LibraryArgs<number>, result: IndexerRule[] } | 
        { key: "locations.list", input: LibraryArgs<null>, result: { id: number, pub_id: number[], node_id: number, name: string, path: string, total_capacity: number | null, available_capacity: number | null, is_archived: boolean, generate_preview_media: boolean, sync_preview_media: boolean, hidden: boolean, date_created: string, node: Node }[] } | 
        { key: "nodeState", input: never, result: NodeState } | 
        { key: "tags.get", input: LibraryArgs<number>, result: Tag | null } | 
        { key: "tags.getExplorerData", input: LibraryArgs<number>, result: ExplorerData } | 
        { key: "tags.getForObject", input: LibraryArgs<number>, result: Tag[] } | 
        { key: "tags.list", input: LibraryArgs<null>, result: Tag[] } | 
        { key: "volumes.list", input: never, result: Volume[] },
    mutations: 
        { key: "files.copyFiles", input: LibraryArgs<FileCopierJobInit>, result: null } | 
        { key: "files.cutFiles", input: LibraryArgs<FileCutterJobInit>, result: null } | 
        { key: "files.decryptFiles", input: LibraryArgs<FileDecryptorJobInit>, result: null } | 
        { key: "files.delete", input: LibraryArgs<number>, result: null } | 
        { key: "files.deleteFiles", input: LibraryArgs<FileDeleterJobInit>, result: null } | 
        { key: "files.duplicateFiles", input: LibraryArgs<FileCopierJobInit>, result: null } | 
        { key: "files.encryptFiles", input: LibraryArgs<FileEncryptorJobInit>, result: null } | 
        { key: "files.eraseFiles", input: LibraryArgs<FileEraserJobInit>, result: null } | 
        { key: "files.setFavorite", input: LibraryArgs<SetFavoriteArgs>, result: null } | 
        { key: "files.setNote", input: LibraryArgs<SetNoteArgs>, result: null } | 
        { key: "jobs.clearAll", input: LibraryArgs<null>, result: null } | 
        { key: "jobs.generateThumbsForLocation", input: LibraryArgs<GenerateThumbsForLocationArgs>, result: null } | 
        { key: "jobs.identifyUniqueFiles", input: LibraryArgs<IdentifyUniqueFilesArgs>, result: null } | 
        { key: "jobs.objectValidator", input: LibraryArgs<ObjectValidatorArgs>, result: null } | 
        { key: "keys.add", input: LibraryArgs<KeyAddArgs>, result: null } | 
        { key: "keys.backupKeystore", input: LibraryArgs<string>, result: null } | 
        { key: "keys.changeMasterPassword", input: LibraryArgs<MasterPasswordChangeArgs>, result: null } | 
        { key: "keys.clearMasterPassword", input: LibraryArgs<null>, result: null } | 
        { key: "keys.deleteFromLibrary", input: LibraryArgs<string>, result: null } | 
        { key: "keys.mount", input: LibraryArgs<string>, result: null } | 
        { key: "keys.restoreKeystore", input: LibraryArgs<RestoreBackupArgs>, result: number } | 
        { key: "keys.setDefault", input: LibraryArgs<string>, result: null } | 
        { key: "keys.syncKeyToLibrary", input: LibraryArgs<string>, result: null } | 
        { key: "keys.unlockKeyManager", input: LibraryArgs<UnlockKeyManagerArgs>, result: null } | 
        { key: "keys.unmount", input: LibraryArgs<string>, result: null } | 
        { key: "keys.unmountAll", input: LibraryArgs<null>, result: null } | 
        { key: "keys.updateAutomountStatus", input: LibraryArgs<AutomountUpdateArgs>, result: null } | 
        { key: "library.create", input: CreateLibraryArgs, result: LibraryConfigWrapped } | 
        { key: "library.delete", input: string, result: null } | 
        { key: "library.edit", input: EditLibraryArgs, result: null } | 
        { key: "locations.addLibrary", input: LibraryArgs<LocationCreateArgs>, result: null } | 
        { key: "locations.create", input: LibraryArgs<LocationCreateArgs>, result: null } | 
        { key: "locations.delete", input: LibraryArgs<number>, result: null } | 
        { key: "locations.fullRescan", input: LibraryArgs<number>, result: null } | 
        { key: "locations.indexer_rules.create", input: LibraryArgs<IndexerRuleCreateArgs>, result: IndexerRule } | 
        { key: "locations.indexer_rules.delete", input: LibraryArgs<number>, result: null } | 
        { key: "locations.quickRescan", input: LibraryArgs<null>, result: null } | 
        { key: "locations.relink", input: LibraryArgs<string>, result: null } | 
        { key: "locations.update", input: LibraryArgs<LocationUpdateArgs>, result: null } | 
        { key: "tags.assign", input: LibraryArgs<TagAssignArgs>, result: null } | 
        { key: "tags.create", input: LibraryArgs<TagCreateArgs>, result: Tag } | 
        { key: "tags.delete", input: LibraryArgs<number>, result: null } | 
        { key: "tags.update", input: LibraryArgs<TagUpdateArgs>, result: null },
    subscriptions: 
        { key: "invalidateQuery", input: never, result: InvalidateOperationEvent } | 
        { key: "jobs.newThumbnail", input: LibraryArgs<null>, result: string } | 
        { key: "locations.online", input: never, result: number[][] } | 
        { key: "p2p.events", input: never, result: Event<PeerMetadata> }
};

/**
 *  These are all possible algorithms that can be used for encryption and decryption
 */
export type Algorithm = "XChaCha20Poly1305" | "Aes256Gcm"

export type AuthOption = { type: "Password", value: string } | { type: "TokenizedPassword", value: string }

export type AutomountUpdateArgs = { uuid: string, status: boolean }

export type BuildInfo = { version: string, commit: string }

/**
 *  ConfigMetadata is a part of node configuration that is loaded before the main configuration and contains information about the schema of the config.
 *  This allows us to migrate breaking changes to the config format between Spacedrive releases.
 */
export type ConfigMetadata = { version: string | null }

/**
 *  TODO
 */
export type ConnectedPeer = { active_connections: number, conn_type: ConnectionType }

export type ConnectionType = "Dialer" | "Listener"

export type CreateLibraryArgs = { name: string, auth: AuthOption, algorithm: Algorithm, hashing_algorithm: HashingAlgorithm }

/**
 *  represents a discovered peer. It can be used to get information about the peer or to initiate an action with it.
 */
export type DiscoveredPeer<TMetadata> = { id: string, metadata: TMetadata, addresses: string[] }

export type EditLibraryArgs = { id: string, name: string | null, description: string | null }

/**
 *  This should be used for passing an encrypted key around.
 * 
 *  This is always `ENCRYPTED_KEY_LEN` (which is `KEY_LEM` + `AEAD_TAG_LEN`)
 */
export type EncryptedKey = number[]

/**
 *  represents an event coming from the network manager.
 *  This is useful for updating your UI when stuff changes on the backend.
 *  You can also interact with some events to cause an event.
 */
export type Event<TMetadata> = { AddListenAddr: string } | { RemoveListenAddr: string } | { PeerDiscovered: DiscoveredPeer<TMetadata> } | { PeerExpired: { id: string, metadata: TMetadata | null } } | { PeerConnected: ConnectedPeer } | { PeerDisconnected: string }

export type ExplorerContext = ({ type:  "Location" } & Location) | ({ type:  "Tag" } & Tag)

export type ExplorerData = { context: ExplorerContext, items: ExplorerItem[] }

export type ExplorerItem = { type: "Path", has_thumbnail: boolean, item: file_path_with_object } | { type: "Object", has_thumbnail: boolean, item: object_with_file_paths }

export type FileCopierJobInit = { source_location_id: number, source_path_id: number, target_location_id: number, target_path: string, target_file_name_suffix: string | null }

export type FileCutterJobInit = { source_location_id: number, source_path_id: number, target_location_id: number, target_path: string }

export type FileDecryptorJobInit = { location_id: number, path_id: number, mount_associated_key: boolean, output_path: string | null, password: string | null, save_to_library: boolean | null }

export type FileDeleterJobInit = { location_id: number, path_id: number }

export type FileEncryptorJobInit = { location_id: number, path_id: number, key_uuid: string, algorithm: Algorithm, metadata: boolean, preview_media: boolean, output_path: string | null }

export type FileEraserJobInit = { location_id: number, path_id: number, passes: string }

export type FilePath = { id: number, is_dir: boolean, cas_id: string | null, integrity_checksum: string | null, location_id: number, materialized_path: string, name: string, extension: string | null, object_id: number | null, parent_id: number | null, key_id: number | null, date_created: string, date_modified: string, date_indexed: string }

export type GenerateThumbsForLocationArgs = { id: number, path: string }

export type GetArgs = { id: number }

/**
 *  This defines all available password hashing algorithms.
 */
export type HashingAlgorithm = { name: "Argon2id", params: Params } | { name: "BalloonBlake3", params: Params }

export type IdentifyUniqueFilesArgs = { id: number, path: string }

export type IndexerRule = { id: number, kind: number, name: string, parameters: number[], date_created: string, date_modified: string }

/**
 *  `IndexerRuleCreateArgs` is the argument received from the client using rspc to create a new indexer rule.
 *  Note that `parameters` field **MUST** be a JSON object serialized to bytes.
 * 
 *  In case of  `RuleKind::AcceptFilesByGlob` or `RuleKind::RejectFilesByGlob`, it will be a
 *  single string containing a glob pattern.
 * 
 *  In case of `RuleKind::AcceptIfChildrenDirectoriesArePresent` or `RuleKind::RejectIfChildrenDirectoriesArePresent` the
 *  `parameters` field must be a vector of strings containing the names of the directories.
 */
export type IndexerRuleCreateArgs = { kind: RuleKind, name: string, parameters: number[] }

export type IndexerRulesInLocation = { date_created: string, location_id: number, indexer_rule_id: number }

export type InvalidateOperationEvent = { key: string, arg: any }

export type JobReport = { id: string, name: string, data: number[] | null, metadata: any | null, date_created: string, date_modified: string, status: JobStatus, task_count: number, completed_task_count: number, message: string, seconds_elapsed: number }

export type JobStatus = "Queued" | "Running" | "Completed" | "Canceled" | "Failed" | "Paused"

export type KeyAddArgs = { algorithm: Algorithm, hashing_algorithm: HashingAlgorithm, key: string, library_sync: boolean, automount: boolean }

/**
 *  Can wrap a query argument to require it to contain a `library_id` and provide helpers for working with libraries.
 */
export type LibraryArgs<T> = { library_id: string, arg: T }

/**
 *  LibraryConfig holds the configuration for a specific library. This is stored as a '{uuid}.sdlibrary' file.
 */
export type LibraryConfig = ({ version: string | null }) & { name: string, description: string, boostrap_progress?: PeerBootstrapProgress }

export type LibraryConfigWrapped = { uuid: string, config: LibraryConfig }

export type Location = { id: number, pub_id: number[], node_id: number, name: string, path: string, total_capacity: number | null, available_capacity: number | null, is_archived: boolean, generate_preview_media: boolean, sync_preview_media: boolean, hidden: boolean, date_created: string }

/**
 *  `LocationCreateArgs` is the argument received from the client using `rspc` to create a new location.
 *  It has the actual path and a vector of indexer rules ids, to create many-to-many relationships
 *  between the location and indexer rules.
 */
export type LocationCreateArgs = { path: string, indexer_rules_ids: number[] }

export type LocationExplorerArgs = { location_id: number, path: string, limit: number, cursor: string | null }

/**
 *  `LocationUpdateArgs` is the argument received from the client using `rspc` to update a location.
 *  It contains the id of the location to be updated, possible a name to change the current location's name
 *  and a vector of indexer rules ids to add or remove from the location.
 * 
 *  It is important to note that only the indexer rule ids in this vector will be used from now on.
 *  Old rules that aren't in this vector will be purged.
 */
export type LocationUpdateArgs = { id: number, name: string | null, generate_preview_media: boolean | null, sync_preview_media: boolean | null, hidden: boolean | null, indexer_rules_ids: number[] }

export type MasterPasswordChangeArgs = { password: string, algorithm: Algorithm, hashing_algorithm: HashingAlgorithm }

export type MediaData = { id: number, pixel_width: number | null, pixel_height: number | null, longitude: number | null, latitude: number | null, fps: number | null, capture_device_make: string | null, capture_device_model: string | null, capture_device_software: string | null, duration_seconds: number | null, codecs: string | null, streams: number | null }

export type Node = { id: number, pub_id: number[], name: string, platform: number, version: string | null, last_seen: string, timezone: string | null, date_created: string }

export type NodeState = { data_path: string }

/**
 *  This should be used for providing a nonce to encrypt/decrypt functions.
 * 
 *  You may also generate a nonce for a given algorithm with `Nonce::generate()`
 */
export type Nonce = { XChaCha20Poly1305: number[] } | { Aes256Gcm: number[] }

export type Object = { id: number, pub_id: number[], name: string | null, extension: string | null, kind: number, size_in_bytes: string, key_id: number | null, hidden: boolean, favorite: boolean, important: boolean, has_thumbnail: boolean, has_thumbstrip: boolean, has_video_preview: boolean, ipfs_id: string | null, note: string | null, date_created: string, date_modified: string, date_indexed: string }

export type ObjectValidatorArgs = { id: number, path: string }

/**
 *  Represents the operating system which the remote peer is running.
 *  This is not used internally and predominantly is designed to be used for display purposes by the embedding application.
 */
export type OperatingSystem = "Windows" | "Linux" | "MacOS" | "IOS" | "Android" | { Other: string }

/**
 *  These parameters define the password-hashing level.
 * 
 *  The greater the parameter, the longer the password will take to hash.
 */
export type Params = "Standard" | "Hardened" | "Paranoid"

/**
 *  TODO
 */
export type PeerBootstrapProgress = { completed: number }

export type PeerMetadata = { name: string, operating_system: OperatingSystem | null, version: string | null }

export type RestoreBackupArgs = { password: string, secret_key: string, path: string }

export type RuleKind = "AcceptFilesByGlob" | "RejectFilesByGlob" | "AcceptIfChildrenDirectoriesArePresent" | "RejectIfChildrenDirectoriesArePresent"

/**
 *  This should be used for passing a salt around.
 * 
 *  You may also generate a salt with `Salt::generate()`
 */
export type Salt = number[]

export type SetFavoriteArgs = { id: number, favorite: boolean }

export type SetNoteArgs = { id: number, note: string | null }

export type Statistics = { id: number, date_captured: string, total_object_count: number, library_db_size: string, total_bytes_used: string, total_bytes_capacity: string, total_unique_bytes: string, total_bytes_free: string, preview_media_bytes: string }

/**
 *  This is a stored key, and can be freely written to the database.
 * 
 *  It contains no sensitive information that is not encrypted.
 */
export type StoredKey = { uuid: string, version: StoredKeyVersion, key_type: StoredKeyType, algorithm: Algorithm, hashing_algorithm: HashingAlgorithm, content_salt: Salt, master_key: EncryptedKey, master_key_nonce: Nonce, key_nonce: Nonce, key: number[], salt: Salt, memory_only: boolean, automount: boolean }

/**
 *  This denotes the type of key. `Root` keys can be used to unlock the key manager, and `User` keys are ordinary keys.
 */
export type StoredKeyType = "User" | "Root"

/**
 *  This denotes the `StoredKey` version.
 */
export type StoredKeyVersion = "V1"

export type Tag = { id: number, pub_id: number[], name: string | null, color: string | null, total_objects: number | null, redundancy_goal: number | null, date_created: string, date_modified: string }

export type TagAssignArgs = { object_id: number, tag_id: number, unassign: boolean }

export type TagCreateArgs = { name: string, color: string }

export type TagUpdateArgs = { id: number, name: string | null, color: string | null }

export type UnlockKeyManagerArgs = { password: string, secret_key: string }

export type Volume = { name: string, mount_point: string, total_capacity: string, available_capacity: string, is_removable: boolean, disk_type: string | null, file_system: string | null, is_root_filesystem: boolean }

export type file_path_with_object = { id: number, is_dir: boolean, cas_id: string | null, integrity_checksum: string | null, location_id: number, materialized_path: string, name: string, extension: string | null, object_id: number | null, parent_id: number | null, key_id: number | null, date_created: string, date_modified: string, date_indexed: string, object: Object | null }

export type object_with_file_paths = { id: number, pub_id: number[], name: string | null, extension: string | null, kind: number, size_in_bytes: string, key_id: number | null, hidden: boolean, favorite: boolean, important: boolean, has_thumbnail: boolean, has_thumbstrip: boolean, has_video_preview: boolean, ipfs_id: string | null, note: string | null, date_created: string, date_modified: string, date_indexed: string, file_paths: FilePath[] }
