/*
 * This file was automatically generated by a script.
 * To regenerate this file, run: pnpm assets gen
 */

import fda from './fda.mp4';
import introvideobg from './introvideobg.webm';
import sdintro from './sdintro.webm';
import mobsdintro from './mobsdintro.mp4';

export { fda, introvideobg, sdintro, mobsdintro };
