name: Cache Rust Dependencies
description: Caches Rust dependencies
inputs:
  save-cache:
    description: Whether to save the Rust cache
    required: false
    default: 'false'
runs:
  using: 'composite'
  steps:
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: rust-deps
        save-if: ${{ inputs.save-cache == "true" }} 
