name: Cache Rust Dependencies
description: Caches Rust dependencies
runs:
  using: 'composite'
  steps:
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: deps-release-v2
