[package]
edition = "2021"
name    = "sd-core-p2p"
version = "0.1.0"

[lints.rust]
# Warns
deprecated            = "warn"
rust_2018_idioms      = { level = "warn", priority = -1 }
trivial_casts         = "warn"
trivial_numeric_casts = "warn"
unused_allocation     = "warn"
unused_qualifications = "warn"
# Forbids
deprecated_in_future = "forbid"

[lints.clippy]
# Warns
all                      = { level = "warn", priority = -1 }
cast_lossless            = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap       = "warn"
cast_precision_loss      = "warn"
cast_sign_loss           = "warn"
complexity               = { level = "warn", priority = -1 }
correctness              = { level = "warn", priority = -1 }
dbg_macro                = "warn"
deprecated_cfg_attr      = "warn"
nursery                  = { level = "warn", priority = -1 }
pedantic                 = { level = "warn", priority = -1 }
perf                     = { level = "warn", priority = -1 }
separated_literal_suffix = "warn"
style                    = { level = "warn", priority = -1 }
suspicious               = { level = "warn", priority = -1 }
unnecessary_cast         = "warn"
unwrap_used              = "warn"
# Allows
missing_errors_doc      = "allow"
module_name_repetitions = "allow"

[dependencies]
# Core Spacedrive Sub-crates
sd-core-cloud-services = { path = "../cloud-services" }

# Spacedrive Sub-crates
sd-cloud-schema = { workspace = true }
sd-crypto       = { path = "../../../crates/crypto" }


# Workspace dependencies
anyhow              = { workspace = true }
async-stream        = { workspace = true }
flume               = { workspace = true }
futures             = { workspace = true }
futures-concurrency = { workspace = true }
iroh                = { workspace = true, features = ["discovery-local-network"] }
quic-rpc            = { workspace = true, features = ["iroh-transport"] }
serde               = { workspace = true, features = ["derive"] }
specta              = { workspace = true, features = ["chrono", "uuid"] }
thiserror           = { workspace = true }
tokio               = { workspace = true, features = ["sync"] }
tokio-util          = { workspace = true }
tracing             = { workspace = true }

# External dependencies
derive_more       = { version = "1.0", features = ["display", "from", "try_into"] }
nested_enum_utils = "0.1"
postcard          = { version = "1.1", features = ["use-std"] }
quic-rpc-derive   = "0.17"
url               = "2.5"
