[package]
name    = "sd-old-p2p-block"
version = "0.1.0"

authors              = ["Oscar Beaumont <oscar@otbeaumont.me>"]
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
# Spacedrive Sub-crates
sd-old-p2p-proto = { path = "../proto" }

# Workspace dependencies
thiserror = { workspace = true }
tokio     = { workspace = true }
tracing   = { workspace = true }
uuid      = { workspace = true }
