// Generated by Spacedrive using Specta - DO NOT EDIT
import Foundation

/// Represents the type of physical storage device
public enum DiskType: Codable {
    case ssd
    case hdd
    case unknown
}

/// Types of file operations
public enum FileOperation: Codable {
    case copy
    case move
    case delete
    case rename
}

/// Represents the filesystem type of the volume
public enum FileSystem: Codable {
    case ntfs
    case fat32
    case ext4
    case apfs
    case exfat
    case btrfs
    case zfs
    case refs
    case other(String)
}

/// Raw filesystem event kinds emitted by the watcher without DB resolution
public enum FsRawEventKind: Codable {
    case create(path: String)
    case modify(path: String)
    case remove(path: String)
    case rename(from: String, to: String)
}

/// Comprehensive metrics for indexing operations
public struct IndexerMetrics: Codable {
    let totalDuration:     let secs: UInt64
    let nanos: UInt32

    let discoveryDuration:     let secs: UInt64
    let nanos: UInt32

    let processingDuration:     let secs: UInt64
    let nanos: UInt32

    let contentDuration:     let secs: UInt64
    let nanos: UInt32

    let filesPerSecond: Float
    let bytesPerSecond: Double
    let dirsPerSecond: Float
    let dbWrites: UInt64
    let dbReads: UInt64
    let batchCount: UInt64
    let avgBatchSize: Float
    let totalErrors: UInt64
    let criticalErrors: UInt64
    let nonCriticalErrors: UInt64
    let skippedPaths: UInt64
    let peakMemoryBytes: UInt64?
    let avgMemoryBytes: UInt64?
}

/// Statistics collected during indexing
public struct IndexerStats: Codable {
    let files: UInt64
    let dirs: UInt64
    let bytes: UInt64
    let symlinks: UInt64
    let skipped: UInt64
    let errors: UInt64
}

/// Output from a completed job
public enum JobOutput: Codable {
    case success
    case filecopy(copiedCount: UInt, totalBytes: UInt64)
    case indexed(stats: IndexerStats, metrics: IndexerMetrics)
    case thumbnailsgenerated(generatedCount: UInt, failedCount: UInt)
    case thumbnailgeneration(generatedCount: UInt64, skippedCount: UInt64, errorCount: UInt64, totalSizeBytes: UInt64)
    case filemove(movedCount: UInt, failedCount: UInt, totalBytes: UInt64)
    case filedelete(deletedCount: UInt, failedCount: UInt, totalBytes: UInt64)
    case duplicatedetection(duplicateGroups: UInt, totalDuplicates: UInt, potentialSavings: UInt64)
    case filevalidation(validatedCount: UInt, issuesFound: UInt, totalBytesValidated: UInt64)
}

/// Current status of a job
public enum JobStatus: Codable {
    case queued
    case running
    case paused
    case completed
    case failed
    case cancelled
}

/// Input for creating a new library
public struct LibraryCreateInput: Codable {
    let name: String
    let path: String?
}

/// Output from library create action dispatch
public struct LibraryCreateOutput: Codable {
    let libraryId: String
    let name: String
    let path: String
}

/// Represents how the volume is mounted in the system
public enum MountType: Codable {
    case system
    case external
    case network
    case virtual
}

/// A path within the Spacedrive Virtual Distributed File System
/// 
/// This is the core abstraction that enables cross-device operations.
/// An SdPath can represent:
/// - A physical file at a specific path on a specific device
/// - A content-addressed file that can be sourced from any device
/// 
/// This enum-based approach enables resilient file operations by allowing
/// content-based paths to be resolved to optimal physical locations at runtime.
public enum SdPath: Codable {
    case physical(deviceId: String, path: String)
    case content(contentId: String)
}

/// Unique fingerprint for a storage volume
public struct VolumeFingerprint: Codable {
String}

/// Classification of volume types for UX and auto-tracking decisions
public enum VolumeType: Codable {
    case primary
    case userdata
    case external
    case secondary
    case system
    case network
    case unknown
}
