// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientQuery } from "./ClientQuery";
import type { CoreResource } from "./CoreResource";
import type { PeerId } from "./PeerId";
import type { PeerMetadata } from "./PeerMetadata";

export type CoreEvent = { key: "InvalidateQuery", data: ClientQuery } | { key: "InvalidateQueryDebounced", data: ClientQuery } | { key: "InvalidateResource", data: CoreResource } | { key: "NewThumbnail", data: { cas_id: string, } } | { key: "Log", data: { message: string, } } | { key: "DatabaseDisconnected", data: { reason: string | null, } } | { key: "PeerPairingRequest", data: { peer_id: PeerId, metadata: PeerMetadata, } };