// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LibraryConfig } from "./LibraryConfig";

export interface LibraryConfigWrapped { uuid: string, config: LibraryConfig, }