// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LibraryQuery =
	| { key: 'GetTags' }
	| { key: 'GetJobHistory' }
	| { key: 'GetLocations' }
	| { key: 'GetLocation'; params: { id: number } }
	| { key: 'GetExplorerDir'; params: { location_id: number; path: string; limit: number } }
	| { key: 'GetLibraryStatistics' };
