// File generated by Prisma Client Rust. DO NOT EDIT

use super::super::{_prisma::*, *};
use super::{SetParam, UncheckedSetParam, UniqueWhereParam, WhereParam, WithParam};
pub const NAME: &str = "data";
pub type Type = Option<Bytes>;
pub type RecursiveSafeType = Type;
pub struct Equals(pub Option<Bytes>);
pub fn equals<T: From<Equals>>(value: Option<Bytes>) -> T {
	Equals(value).into()
}
impl From<Equals> for WhereParam {
	fn from(Equals(v): Equals) -> Self {
		WhereParam::Data(_prisma::read_filters::BytesNullableFilter::Equals(v))
	}
}
::prisma_client_rust::scalar_where_param_fns!(_prisma::read_filters::BytesNullableFilter, Data, {
	fn in_vec(_: Vec<Bytes>) -> InVec;
	fn not_in_vec(_: Vec<Bytes>) -> NotInVec;
	fn not(_: Option<Bytes>) -> Not;
});
pub struct Order(SortOrder);
pub fn order<T: From<Order>>(v: SortOrder) -> T {
	Order(v).into()
}
impl From<Order> for super::OrderByWithRelationParam {
	fn from(Order(v): Order) -> Self {
		Self::Data(v)
	}
}
pub struct Set(pub Option<Bytes>);
impl From<Set> for SetParam {
	fn from(Set(v): Set) -> Self {
		Self::Data(_prisma::write_params::BytesNullableParam::Set(v))
	}
}
pub fn set<T: From<Set>>(value: Option<Bytes>) -> T {
	Set(value).into()
}
pub struct UpdateOperation(pub _prisma::write_params::BytesNullableParam);
impl From<UpdateOperation> for SetParam {
	fn from(UpdateOperation(v): UpdateOperation) -> Self {
		Self::Data(v)
	}
}
impl From<Set> for UncheckedSetParam {
	fn from(Set(v): Set) -> Self {
		Self::Data(_prisma::write_params::BytesNullableParam::Set(v))
	}
}
impl From<UpdateOperation> for UncheckedSetParam {
	fn from(UpdateOperation(v): UpdateOperation) -> Self {
		Self::Data(v)
	}
}
pub struct Select;
impl Into<super::SelectParam> for Select {
	fn into(self) -> super::SelectParam {
		super::SelectParam::Data(self)
	}
}
impl Into<::prisma_client_rust::Selection> for Select {
	fn into(self) -> ::prisma_client_rust::Selection {
		::prisma_client_rust::sel(NAME)
	}
}
pub struct Include;
impl Into<super::IncludeParam> for Include {
	fn into(self) -> super::IncludeParam {
		super::IncludeParam::Data(self)
	}
}
impl Into<::prisma_client_rust::Selection> for Include {
	fn into(self) -> ::prisma_client_rust::Selection {
		::prisma_client_rust::sel(NAME)
	}
}
