name: "Rust Cache"
description: "A GitHub Action that implements smart caching for rust/cargo projects with sensible defaults."
author: "Arpad Borsos <arpad.borsos@googlemail.com>"
inputs:
  key:
    description: 'An explicit key for restoring and saving the cache'
    required: true
  restore-keys:
    description: 'An ordered list of keys to use for restoring the cache if no cache hit occurred for key'
    required: false
  working-directory:
    description: "The working directory this action should operate in"
    required: false
  target-dir:
    description: "The target dir that should be cleaned and persisted, defaults to `./target`"
    required: false
  cache-on-failure:
    description: "Cache even if the build fails. Defaults to false"
    required: false
outputs:
  cache-hit:
    description: "A boolean value that indicates an exact match was found"
runs:
  using: "node12"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
  post-if: "success() || env.CACHE_ON_FAILURE == 'true'"
branding:
  icon: "archive"
  color: "gray-dark"
