// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "db.tags", input: string, result: Record<string, Tag> } | 
        { key: "dbs", input: never, result: Array<string> } | 
        { key: "file_path.list", input: string, result: Array<FilePath> },
    mutations: 
        { key: "createDatabase", input: never, result: string } | 
        { key: "file_path.create", input: string, result: FilePath } | 
        { key: "removeDatabases", input: never, result: null },
    subscriptions: never
};

export interface Color { red: number, green: number, blue: number }

export interface FilePath { id: number, path: string, file: number | null }

export interface Tag { color: Color, name: string }
