import { FetchTransport, createClient } from '@rspc/client';
import { createReactQueryHooks } from '@rspc/react';
import { QueryClient } from '@tanstack/react-query';

import type { Procedures } from './bindings';

export * from './bindings';

// These are generated by rspc in Rust for you.

const rspcClient = createClient<Procedures>({
	transport: new FetchTransport('http://localhost:9000/rspc')
});

const queryClient = new QueryClient({
	defaultOptions: {
		queries: {
			suspense: true
		},
		mutations: {
			onSuccess: () => queryClient.invalidateQueries()
		}
	}
});

const rspc = createReactQueryHooks<Procedures>();

export { rspc, rspcClient, queryClient };
